homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # # User Authentication
  auth_providers:
   - type: legacy_api_password
     api_password: !secret api_password
   - type: homeassistant

# Customizations
  customize: !include customize.yaml

# customizer:
  # custom_ui: hosted

# Enables the frontend
frontend: !include frontend.yaml

# Enables configuration UI
config:

ffmpeg:

#Enables Map
map:

mobile_app:

system_log:
  max_entries: 100  
  
http:
 ssl_certificate: !secret http_ssl_certificate
 ssl_key: !secret http_ssl_key
 base_url: !secret http_base_url
 server_port: 8123

duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_access_token

updater:

# Discover some devices automatically
discovery: !include discovery.yaml

# allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history: !include history.yaml

# View all events in a logbook
logbook: !include logbook.yaml

#recorder
recorder: !include recorder.yaml

# Track the sun
sun:
  monitored_conditions:
    - elevation
    - max_elevation
    - daylight
    - sunrise
    - sunset
  scan_interval:
    minutes: 10   

# Sensors
sensor: !include sensors.yaml

# Text to speech
tts:
  platform: google_translate

# Google  
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret
  track_new_calendar: true

#  Groups
group: !include groups.yaml

#Media Players
media_player: !include media_players.yaml

apple_tv: !include apple_tv.yaml

####   Device Tracking
device_tracker: !include device_trackers.yaml

######  Automation   
automation: !include automations.yaml

######  Scripts
script: !include scripts.yaml

#####  Input Boolean
input_boolean: !include input_boolean.yaml

#####  Input Select
input_select: !include includes/input_select.yaml

#  Input Number
input_number: !include includes/input_number.yaml

## Notifications
notify: !include includes/notify.yaml

# Scenes
scene: !include scenes.yaml

# Switches
switch: !include switches.yaml

# iOS
ios:

### Alexa
alexa:

### Thermostat
climate: !include climate.yaml

### IFTTT   
ifttt: !include ifttt.yaml

## Binary Sensors  
binary_sensor: !include_dir_merge_list binary_sensor

## Cameras
camera: !include cameras.yaml

## Remotes
remote: !include remote.yaml

####MQTT#####
mqtt: !include mqtt.yaml

#Intent Scripts
intent_script: !include intent_script.yaml

panel_custom: !include panel_custom.yaml

#System Health  
system_health:

#Speed Test
speedtestdotnet: !include speedtestdotnet.yaml

#Shell Commands
shell_command: !include shell_command.yaml

#Persons
person: # !include persons.yaml
  
#Apple Homekit
homekit: !include homekit.yaml

#Streams
stream:

#Image Processing
image_processing: !include image_processing.yaml

hive: !include hive.yaml

tuya:
  username: !secret tuya_username
  password: !secret tuya_password
  country_code: 1
  platform: jinvoo_smart
  
geo_location:
  - platform: usgs_earthquakes_feed
    feed_type: 'past_week_m10_earthquakes'
    radius: 50
    minimum_magnitude: 1.0
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    
timer: !include timers.yaml

emulated_hue: !include emulated_hue.yaml
  
spotify:
  client_id: 4b782948981f489fb0859ac09a6252c0
  client_secret: 04a91f2d488547b3a774fd5004b6ef08

zwave:
  usb_path: /dev/ttyUSB0

zha:
  usb_path: /dev/ttyUSB1
  database_path: /home/homeassistant/.homeassistant/zigbee.db

lovelace: !include lovelace_resources.yaml

airvisual:
  api_key: !secret airvisual_api_key
  
# panasonic_viera:
  # host: 192.168.55.231
  # name: Livingroom TV