- platform: html5
  name: HTML5Notify
  vapid_pub_key: !secret vapid_pub_key
  vapid_prv_key: !secret vapid_prv_key
  vapid_email: !secret vapid_email

- platform: alexa_media
  name: alexa_media